/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ru.wts;

import java.io.File;
import java.net.URI;
import java.net.URISyntaxException;

public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) throws URISyntaxException {
        App app = new App();
        System.out.println(app.getGreeting());
        URI sourceUri = App.class.getResource("/props/app.properties").toURI();
        File f1 = new File(sourceUri);
        System.out.println("file exists?: " + f1.exists());
    }
}
